### PR TITLE
update vendor of go-dockerclient which fixed compatibility issue with docker 1.12 RC

### PR DESCRIPTION
**Pull request by missedone**
fixed issue #112

### CODE REVIEW

**Comment by missedone** [comment]
see the actually fix at upstream lib go-dockerclient: https://github.com/fsouza/go-dockerclient/commit/e84af599e9188dd184f58589d08cdebb4237c1fb

**Comment by ctrlok** [comment]
@ybogdanov @romank87 Any comments?

**Comment by kudos** [comment]
@missedone this seems to be missing vendored libraries.

**Comment by IlyaSemenov** [comment]
@kudos See my other PR which includes all missing vendor libraries.

**Comment by missedone** [comment]
closed, in favor of PR #115

**Pull request closed without merging**
