### PR TITLE
Docker 1.12 compatibility, make integration tests run under Docker for Mac

### PR DESCRIPTION
**Pull request by ybogdanov**

### CODE REVIEW

**Comment by ctrlok** [comment]
Maybe we should create Vagrantfile for that cases?

**Comment by ybogdanov** [comment]
How about teamcity?

**Comment by ctrlok** [comment]
TeamCity is a good choice if you don't have any requirements for integration tests from external contributors. ALSO, vagrant is a good choice for testing with many versions of Docker daemon.

**Comment by ybogdanov** [comment]
How about TravisCI?

**Comment by ctrlok** [comment]
Hm. Travis was updated their base image, so now we can update docker with sudo. so TravisCI is a cool alternative.

**Pull request merged**
